"""Validate a project previously generated by Samsarix CLI."""

import json
from pathlib import Path

import click

from samsarix_cli.validation import check_project


@click.command("check")
@click.argument(
    "project",
    required=False,
    default=".",
    type=click.Path(path_type=Path, exists=True, file_okay=False, resolve_path=True),
)
@click.option("--json", "as_json", is_flag=True, help="Emit stable JSON for automation.")
def check(project: Path, as_json: bool) -> None:
    """Check the generated-project contract at PROJECT (defaults to cwd)."""
    result = check_project(project)

    if as_json:
        click.echo(
            json.dumps(
                {
                    "issues": list(result.issues),
                    "project": str(result.project),
                    "valid": result.is_valid,
                },
                indent=2,
                sort_keys=True,
            )
        )
    elif result.is_valid:
        click.echo(f"OK: {result.project} is a valid Samsarix-generated project.")
    else:
        click.echo(f"Check failed for {result.project}:", err=True)
        for issue in result.issues:
            click.echo(f"  - {issue}", err=True)

    if not result.is_valid:
        raise click.exceptions.Exit(1)
