"""Built-in, dependency-independent project template definitions."""

from dataclasses import dataclass
from textwrap import dedent


@dataclass(frozen=True, slots=True)
class TemplateSpec:
    """Metadata shown by the CLI and used during rendering."""

    name: str
    summary: str
    run_command: str


TEMPLATE_SPECS = (
    TemplateSpec(
        name="fastapi",
        summary="Small HTTP API with a health endpoint and Uvicorn runner.",
        run_command="PROJECT_NAME",
    ),
    TemplateSpec(
        name="flask",
        summary="Small Flask service with a health endpoint.",
        run_command="PROJECT_NAME",
    ),
    TemplateSpec(
        name="streamlit",
        summary="Interactive Streamlit application with one testable core function.",
        run_command="python -m streamlit run src/MODULE_NAME/main.py",
    ),
    TemplateSpec(
        name="discord",
        summary="Discord bot with explicit token validation and minimal intents.",
        run_command="PROJECT_NAME",
    ),
)

TEMPLATE_BY_NAME = {spec.name: spec for spec in TEMPLATE_SPECS}
TEMPLATE_NAMES = tuple(TEMPLATE_BY_NAME)
DEFAULT_TEMPLATE = "fastapi"


def _pyproject(
    *,
    project_name: str,
    module_name: str,
    dependencies: tuple[str, ...],
    script_target: str | None,
) -> str:
    lines = [
        "[build-system]",
        'requires = ["setuptools>=83,<84", "wheel>=0.45,<1"]',
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        f'name = "{project_name}"',
        'version = "0.1.0"',
        f'description = "A {project_name} project generated by Samsarix CLI"',
        'readme = "README.md"',
        'requires-python = ">=3.11"',
        "dependencies = [",
        *(f'    "{dependency}",' for dependency in dependencies),
        "]",
    ]
    if script_target is not None:
        command_name = project_name.lower().replace("_", "-")
        lines.extend(
            (
                "",
                "[project.scripts]",
                f'{command_name} = "{module_name}.main:{script_target}"',
            )
        )

    lines.extend(
        (
            "",
            "[project.optional-dependencies]",
            "dev = [",
            '    "pytest>=8,<10",',
            '    "ruff>=0.11,<1",',
            "]",
            "",
            "[tool.setuptools.packages.find]",
            'where = ["src"]',
            "namespaces = false",
            "",
            "[tool.pytest.ini_options]",
            'testpaths = ["tests"]',
            "",
            "[tool.ruff]",
            "line-length = 100",
            'target-version = "py311"',
        )
    )
    return "\n".join(lines) + "\n"


def _readme(
    *,
    project_name: str,
    module_name: str,
    template_name: str,
    run_command: str,
    configuration: str,
) -> str:
    return (
        dedent(
            f"""
            # {project_name}

            A standalone Python project generated with the Samsarix CLI `{template_name}` template.
            It has no runtime dependency on Samsarix CLI or on a hosted service.

            ## Requirements

            - Python 3.11 or newer

            ## Setup

            ```bash
            python -m venv .venv
            ```

            Activate the environment:

            ```powershell
            # Windows PowerShell
            .venv\\Scripts\\Activate.ps1
            ```

            ```bash
            # macOS or Linux
            source .venv/bin/activate
            ```

            Install the application and development tools:

            ```bash
            python -m pip install --upgrade pip "setuptools>=83,<84"
            python -m pip install -e ".[dev]"
            ```

            ## Run

            ```bash
            {run_command}
            ```

            {configuration}

            ## Verify

            ```bash
            pytest
            ruff check .
            ruff format --check .
            ```

            If Samsarix CLI is installed, its structural check is also available:

            ```bash
            samsarix check .
            ```

            ## Layout

            - `src/{module_name}/`: application source
            - `tests/`: focused tests
            - `.samsarix/project.json`: generator metadata used by `samsarix check`

            ## License

            No license is selected for generated projects. Choose and add a license before
            redistributing this project.
            """
        ).strip()
        + "\n"
    )


def _common_files(project_name: str, module_name: str) -> dict[str, str]:
    return {
        ".gitignore": dedent(
            """
            __pycache__/
            *.py[cod]
            .coverage
            .env
            .pytest_cache/
            .ruff_cache/
            .venv/
            build/
            dist/
            *.egg-info/
            """
        ).lstrip(),
        f"src/{module_name}/__init__.py": (
            f'"""{project_name} application package."""\n\n__version__ = "0.1.0"\n'
        ),
    }


def _fastapi_files(project_name: str, module_name: str) -> dict[str, str]:
    command_name = project_name.lower().replace("_", "-")
    files = _common_files(project_name, module_name)
    files.update(
        {
            "pyproject.toml": _pyproject(
                project_name=project_name,
                module_name=module_name,
                dependencies=("fastapi>=0.100,<1", "uvicorn>=0.23,<1"),
                script_target="main",
            ),
            "README.md": _readme(
                project_name=project_name,
                module_name=module_name,
                template_name="fastapi",
                run_command=command_name,
                configuration=(
                    "The service binds to `127.0.0.1:8000` by default. Open "
                    "`http://127.0.0.1:8000/health` to verify it."
                ),
            ),
            f"src/{module_name}/main.py": dedent(
                f'''\
                """HTTP entry point for {project_name}."""

                from fastapi import FastAPI

                app = FastAPI(title="{project_name}")


                def health_payload() -> dict[str, str]:
                    """Return the stable readiness response."""
                    return {{"status": "ok"}}


                @app.get("/health")
                async def health() -> dict[str, str]:
                    """Report that the process is ready to accept requests."""
                    return health_payload()


                def main() -> None:
                    """Run the development server on the loopback interface."""
                    import uvicorn

                    uvicorn.run("{module_name}.main:app", host="127.0.0.1", port=8000)


                if __name__ == "__main__":
                    main()
                '''
            ),
            "tests/test_app.py": dedent(
                f"""\
                from {module_name}.main import health_payload


                def test_health_payload() -> None:
                    assert health_payload() == {{"status": "ok"}}
                """
            ),
        }
    )
    return files


def _flask_files(project_name: str, module_name: str) -> dict[str, str]:
    command_name = project_name.lower().replace("_", "-")
    files = _common_files(project_name, module_name)
    files.update(
        {
            "pyproject.toml": _pyproject(
                project_name=project_name,
                module_name=module_name,
                dependencies=("flask>=3,<4",),
                script_target="main",
            ),
            "README.md": _readme(
                project_name=project_name,
                module_name=module_name,
                template_name="flask",
                run_command=command_name,
                configuration=(
                    "The service binds to `127.0.0.1:8000` by default. Open "
                    "`http://127.0.0.1:8000/health` to verify it."
                ),
            ),
            f"src/{module_name}/main.py": dedent(
                f'''\
                """HTTP entry point for {project_name}."""

                from flask import Flask

                app = Flask(__name__)


                def health_payload() -> dict[str, str]:
                    """Return the stable readiness response."""
                    return {{"status": "ok"}}


                @app.get("/health")
                def health() -> dict[str, str]:
                    """Report that the process is ready to accept requests."""
                    return health_payload()


                def main() -> None:
                    """Run Flask's development server on the loopback interface."""
                    app.run(host="127.0.0.1", port=8000, debug=False)


                if __name__ == "__main__":
                    main()
                '''
            ),
            "tests/test_app.py": dedent(
                f"""\
                from {module_name}.main import health_payload


                def test_health_payload() -> None:
                    assert health_payload() == {{"status": "ok"}}
                """
            ),
        }
    )
    return files


def _streamlit_files(project_name: str, module_name: str) -> dict[str, str]:
    run_command = f"python -m streamlit run src/{module_name}/main.py"
    files = _common_files(project_name, module_name)
    files.update(
        {
            "pyproject.toml": _pyproject(
                project_name=project_name,
                module_name=module_name,
                dependencies=("streamlit>=1.40,<2",),
                script_target=None,
            ),
            "README.md": _readme(
                project_name=project_name,
                module_name=module_name,
                template_name="streamlit",
                run_command=run_command,
                configuration=(
                    "Streamlit prints the local application URL when it starts. The starter does "
                    "not collect credentials or call an external API."
                ),
            ),
            f"src/{module_name}/main.py": dedent(
                f'''\
                """Streamlit entry point for {project_name}."""

                import streamlit as st


                def greeting(name: str) -> str:
                    """Build the message shown by the application."""
                    cleaned_name = name.strip()
                    return f"Hello, {{cleaned_name or 'world'}}!"


                def main() -> None:
                    """Render the application."""
                    st.set_page_config(page_title="{project_name}")
                    st.title("{project_name}")
                    name = st.text_input("Your name")
                    st.write(greeting(name))


                if __name__ == "__main__":
                    main()
                '''
            ),
            "tests/test_app.py": dedent(
                f"""\
                from {module_name}.main import greeting


                def test_greeting_uses_a_safe_default() -> None:
                    assert greeting("  ") == "Hello, world!"


                def test_greeting_trims_the_name() -> None:
                    assert greeting(" Ada ") == "Hello, Ada!"
                """
            ),
        }
    )
    return files


def _discord_files(project_name: str, module_name: str) -> dict[str, str]:
    command_name = project_name.lower().replace("_", "-")
    files = _common_files(project_name, module_name)
    files.update(
        {
            "pyproject.toml": _pyproject(
                project_name=project_name,
                module_name=module_name,
                dependencies=("discord.py>=2.4,<3",),
                script_target="main",
            ),
            "README.md": _readme(
                project_name=project_name,
                module_name=module_name,
                template_name="discord",
                run_command=command_name,
                configuration=dedent(
                    """
                    Create a Discord application and bot, then expose the token only through the
                    process environment. Never commit it:

                    ```powershell
                    # Windows PowerShell
                    $env:DISCORD_TOKEN = "replace-with-your-token"
                    ```

                    ```bash
                    # macOS or Linux
                    export DISCORD_TOKEN="replace-with-your-token"
                    ```

                    The starter requests only the default gateway intents and responds to the
                    `hello` slash command. Invite and permission configuration remains an owner
                    task.
                    """
                ).strip(),
            ),
            f"src/{module_name}/main.py": dedent(
                f'''\
                """Discord entry point for {project_name}."""

                import os

                import discord


                def discord_token() -> str:
                    """Load the bot token without logging or persisting it."""
                    token = os.environ.get("DISCORD_TOKEN", "").strip()
                    if not token:
                        raise RuntimeError(
                            "DISCORD_TOKEN is required. Set it in the process environment."
                        )
                    return token


                class StarterClient(discord.Client):
                    """Minimal client that registers one slash command."""

                    def __init__(self) -> None:
                        super().__init__(intents=discord.Intents.default())
                        self.tree = discord.app_commands.CommandTree(self)

                    async def setup_hook(self) -> None:
                        await self.tree.sync()


                client = StarterClient()


                @client.tree.command(name="hello", description="Say hello")
                async def hello(interaction: discord.Interaction) -> None:
                    """Respond without exposing message-content access."""
                    await interaction.response.send_message("Hello from {project_name}!")


                def main() -> None:
                    """Run the bot until interrupted."""
                    client.run(discord_token(), log_handler=None)


                if __name__ == "__main__":
                    main()
                '''
            ),
            "tests/test_config.py": dedent(
                f"""\
                import pytest

                from {module_name}.main import discord_token


                def test_discord_token_is_required(monkeypatch: pytest.MonkeyPatch) -> None:
                    monkeypatch.delenv("DISCORD_TOKEN", raising=False)
                    with pytest.raises(RuntimeError, match="DISCORD_TOKEN is required"):
                        discord_token()


                def test_discord_token_is_trimmed(monkeypatch: pytest.MonkeyPatch) -> None:
                    monkeypatch.setenv("DISCORD_TOKEN", " test-token ")
                    assert discord_token() == "test-token"
                """
            ),
        }
    )
    return files


_RENDERERS = {
    "fastapi": _fastapi_files,
    "flask": _flask_files,
    "streamlit": _streamlit_files,
    "discord": _discord_files,
}


def render_project(project_name: str, module_name: str, template_name: str) -> dict[str, str]:
    """Render all tracked text files for one built-in starter."""
    try:
        renderer = _RENDERERS[template_name]
    except KeyError as exc:
        raise ValueError(f"Unknown template: {template_name}") from exc
    return renderer(project_name, module_name)
